import pandas as pd


iris = pd.read_csv(r"C:\Users\user\Desktop\current coding\data science\iris.csv")
print(iris)
print(iris.shape)
print(iris["sepal_length"].mean(),iris["sepal_width"].mean(),iris["petal_length"].mean(),iris["petal_width"].mean())
print("")
"""print(iris[iris["species"]=="setosa"].count())
print(iris[iris["species"]=="versicolor"].count())
print(iris[iris["species"]=="virginica"].count())"""
print(iris["species"].value_counts())
print(iris.tail(n=8))
setosa = pd.DataFrame(iris[iris["species"]=="setosa"])
print(setosa)
print("")
print(setosa[setosa["petal_length"]>setosa["petal_length"].mean()])
print("")
print(setosa["sepal_length"].mean())
print(setosa["sepal_length"].min())
print(setosa["sepal_length"].max())
print("")
print(setosa["sepal_width"].mean())
print(setosa["sepal_width"].min())
print(setosa["sepal_width"].max())
print("")
print(setosa["petal_length"].mean())
print(setosa["petal_length"].min())
print(setosa["petal_length"].max())
print("")
print(setosa["petal_width"].mean())
print(setosa["petal_width"].min())
print(setosa["petal_width"].max())

print("")
iris["code"] = iris["species"].replace({"setosa":1,"versicolor":2,"virginica":3})
print(iris)
print("")
print(iris.sort_values("petal_length",ascending=True))
print(iris.groupby("species").mean())
iris["species"] = iris["species"].str.upper()
print(iris)
print(iris.agg({"sepal_length":["mean","median"],"sepal_width":["mean","median"]}))
iris.rename(columns={"sepal_width":"sepal width","sepal_length":"sepal length","petal_width":"petal width","petal_length":"petal length"},inplace=True)
print(iris)
